"""
evaluate.py — loads a trained checkpoint and computes real Accuracy,
Precision, Recall, F1, and ROC-AUC on a given split (train/val/test), plus
CMAS explainability scores. Writes results/results.json and
results/metrics_report.txt.

Usage:
    python evaluate.py --checkpoint checkpoints/best_model_multimodal.pt --split test --config config.yaml
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import numpy as np
import torch
import yaml
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)
from torch.utils.data import DataLoader
from tqdm import tqdm

from dataset.dataset import FakeAVCelebDataset, collate_fn
from explainability.attribution import aggregate_cmas, explain_batch
from metrics.threshold import apply_threshold, find_best_threshold
from models.fusion import CMASDeepfakeDetector
from train import build_model, prepare_batch
from utils.logging_utils import get_logger
from utils.seed import get_device, set_seed


def parse_args():
    parser = argparse.ArgumentParser(description="Evaluate a trained CMAS deepfake detector.")
    parser.add_argument("--checkpoint", type=str, required=True)
    parser.add_argument("--split", type=str, default="test", choices=["train", "val", "test"])
    parser.add_argument("--config", type=str, default="config.yaml")
    parser.add_argument("--compute_cmas", action="store_true", default=True)
    parser.add_argument("--no_cmas", dest="compute_cmas", action="store_false")
    parser.add_argument("--max_cmas_samples", type=int, default=200, help="IG is expensive; cap the number of samples used for CMAS.")
    parser.add_argument(
        "--tune_threshold", action="store_true",
        help="Find the Youden's-J-maximizing decision threshold (sensitivity+specificity-1, "
             "robust to class imbalance) on the VAL split (not the split being evaluated), then "
             "report metrics under BOTH the default 0.5/argmax threshold and the tuned threshold. "
             "Does not modify the checkpoint or model weights — this is a no-retraining fix for a "
             "poorly-calibrated default decision boundary. Checks for and flags a degenerate "
             "(always-predict-one-class) result rather than silently reporting it. See "
             "metrics/threshold.py for why this exists and why Youden's J rather than F1.",
    )
    return parser.parse_args()


@torch.no_grad()
def run_forward_pass(model, loader, device, sample_rate: int):
    """Runs the model over a full split and returns (labels, probs) as plain
    Python lists. Factored out so --tune_threshold can reuse it for the val
    split without duplicating the batch loop."""
    all_probs, all_labels = [], []
    for batch in tqdm(loader, desc="Forward pass"):
        if batch is None:  # entire mini-batch was unreadable files — see dataset.py collate_fn
            continue
        visual_input, audio_input, labels = prepare_batch(batch, model, device, sample_rate=sample_rate)
        visual_embed, audio_embed = model.encode(visual_input, audio_input)
        logits = model.classify_from_embeddings(visual_embed, audio_embed)
        probs = torch.softmax(logits, dim=-1)[:, 1]
        all_probs.extend(probs.cpu().numpy().tolist())
        all_labels.extend(labels.cpu().numpy().tolist())
    return all_labels, all_probs


def build_loader(cfg: dict, manifest_path: str):
    ds = FakeAVCelebDataset(
        manifest_path,
        cache_dir=cfg["paths"]["cache_dir"],
        num_frames=cfg["model"]["num_frames"],
        sample_rate=cfg["audio"]["sample_rate"],
        max_duration_sec=cfg["audio"]["max_duration_sec"],
        split="test",  # no augmentation at eval time regardless of split name
    )
    return DataLoader(
        ds, batch_size=cfg["training"]["batch_size"], shuffle=False,
        num_workers=cfg["training"]["num_workers"], collate_fn=collate_fn,
    )


def main():
    args = parse_args()
    with open(args.config) as f:
        cfg = yaml.safe_load(f)

    set_seed(cfg["seed"])
    device = get_device(cfg["device"]["auto_detect"])
    logger = get_logger("evaluate", cfg["paths"]["log_dir"], filename=f"evaluate_{args.split}.log")

    # weights_only=False: PyTorch >=2.6 defaults torch.load to weights_only=True,
    # which refuses to unpickle anything beyond a narrow safe-list (tensors,
    # basic Python types). Our checkpoints also carry a `config` dict and a
    # `val_metrics` dict that can legitimately need broader unpickling support
    # depending on exactly what ended up in them (see train.py's evaluate()
    # for the numpy-scalar issue this ran into in practice). This is safe here
    # specifically because these checkpoints are self-generated by train.py in
    # this same repo, not arbitrary/untrusted files — weights_only=False is
    # exactly the trust boundary PyTorch's own docs describe as acceptable to
    # cross for files you trust the origin of.
    ckpt = torch.load(args.checkpoint, map_location=device, weights_only=False)
    mode = ckpt.get("mode", "multimodal")
    model = build_model(cfg, mode, device)
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()
    logger.info(f"Loaded checkpoint {args.checkpoint} (mode={mode}, trained epoch={ckpt.get('epoch')})")

    manifest_key = f"{args.split}_manifest"
    loader = build_loader(cfg, cfg["paths"][manifest_key])

    all_probs, all_preds, all_labels = [], [], []
    all_attributions = []
    cmas_samples_used = 0

    with torch.no_grad():
        for batch in tqdm(loader, desc=f"Evaluating on {args.split}"):
            if batch is None:  # entire mini-batch was unreadable files — see dataset.py collate_fn
                continue
            visual_input, audio_input, labels = prepare_batch(batch, model, device, sample_rate=cfg["audio"]["sample_rate"])
            visual_embed, audio_embed = model.encode(visual_input, audio_input)
            # classify_from_embeddings is the single source of truth for the
            # mode-dependent fusion/classifier branching (see models/fusion.py)
            # — this used to be a hand-duplicated if/elif chain here that could
            # drift out of sync with the real forward() logic; found and fixed
            # during review.
            logits = model.classify_from_embeddings(visual_embed, audio_embed)

            probs = torch.softmax(logits, dim=-1)[:, 1]
            all_probs.extend(probs.cpu().numpy().tolist())
            all_preds.extend(logits.argmax(dim=-1).cpu().numpy().tolist())
            all_labels.extend(labels.cpu().numpy().tolist())

            if args.compute_cmas and mode == "multimodal" and cmas_samples_used < args.max_cmas_samples:
                # IG needs gradients enabled even though we're in an eval loop.
                with torch.enable_grad():
                    ve = visual_embed.clone().detach().requires_grad_(True)
                    ae = audio_embed.clone().detach().requires_grad_(True)
                    results = explain_batch(
                        model, ve, ae, logits, labels, batch["modality_gt"].to(device),
                        batch["video_path"], method=cfg["explainability"]["attribution_method"],
                        ig_n_steps=cfg["explainability"]["ig_n_steps"],
                    )
                all_attributions.extend(results)
                cmas_samples_used += len(results)

    def compute_metric_dict(labels_list, preds_list, probs_list) -> dict:
        d = {
            "accuracy": float(accuracy_score(labels_list, preds_list)),
            "precision": float(precision_score(labels_list, preds_list, zero_division=0)),
            "recall": float(recall_score(labels_list, preds_list, zero_division=0)),
            "f1": float(f1_score(labels_list, preds_list, zero_division=0)),
        }
        if len(set(labels_list)) > 1:
            d["roc_auc"] = float(roc_auc_score(labels_list, probs_list))
        else:
            d["roc_auc"] = None
        cm_local = confusion_matrix(labels_list, preds_list, labels=[0, 1])
        d["confusion_matrix"] = cm_local.tolist()
        return d

    metrics = {
        "split": args.split,
        "n_samples": len(all_labels),
        # "default" = argmax(logits), equivalent to a fixed 0.5 threshold on
        # P(FAKE). Kept even when --tune_threshold is used, for direct
        # before/after comparison in the same report.
        "default_threshold": 0.5,
    }
    metrics.update(compute_metric_dict(all_labels, all_preds, all_probs))
    if metrics["roc_auc"] is None:
        logger.warning("Only one class present in this split; ROC-AUC is undefined.")
    if "roc_auc" in metrics and metrics["roc_auc"] is not None:
        fpr, tpr, _ = roc_curve(all_labels, all_probs)
        metrics["roc_curve"] = {"fpr": fpr.tolist(), "tpr": tpr.tolist()}

    if args.tune_threshold:
        if args.split == "val":
            logger.warning(
                "--tune_threshold was requested while evaluating the val split itself; "
                "tuning and reporting on the same split would be circular. Tuning against "
                "the val split's own forward pass (which is what you just ran) instead of "
                "a separate one, but be aware this is not a held-out threshold in that case."
            )
            val_labels, val_probs = all_labels, all_probs
        else:
            logger.info("Running a forward pass on the val split to tune the decision threshold...")
            val_loader = build_loader(cfg, cfg["paths"]["val_manifest"])
            val_labels, val_probs = run_forward_pass(model, val_loader, device, cfg["audio"]["sample_rate"])

        threshold_result = find_best_threshold(val_labels, val_probs, metric="youden")
        logger.info(
            f"Tuned threshold (on val, metric=youden): {threshold_result.threshold:.4f} "
            f"(Youden's J at this threshold: {threshold_result.metric_value_at_threshold:.4f}, "
            f"val recall_real={threshold_result.recall_real_at_threshold:.3f}, "
            f"val recall_fake={threshold_result.recall_fake_at_threshold:.3f})"
        )
        if threshold_result.is_degenerate:
            logger.warning(
                "TUNED THRESHOLD IS DEGENERATE — it predicts (almost) only one class. "
                "Do not report metrics_at_tuned_threshold below as a real result; see "
                "metrics/threshold.py and check whether this model has any usable "
                "discrimination between REAL and FAKE at all."
            )

        tuned_preds = apply_threshold(all_probs, threshold_result.threshold)
        tuned_metrics = compute_metric_dict(all_labels, tuned_preds, all_probs)
        metrics["tuned_threshold"] = threshold_result.threshold
        metrics["tuned_threshold_metric"] = "youden"
        metrics["tuned_threshold_source"] = "val" if args.split != "val" else "val (same split — not held out)"
        # Surfaced directly in the JSON/report, not just a console log line —
        # a console warning is easy to miss in a long Colab log, which is
        # exactly how the earlier degenerate audio-only threshold went
        # unnoticed until manually inspecting the confusion matrix.
        metrics["tuned_threshold_is_degenerate"] = threshold_result.is_degenerate
        metrics["metrics_at_tuned_threshold"] = tuned_metrics

    if args.compute_cmas and mode == "multimodal" and all_attributions:
        cmas_summary = aggregate_cmas(all_attributions)
        metrics["cmas"] = cmas_summary
        metrics["cmas_per_sample"] = [
            {
                "video_path": r.video_path,
                "predicted_label": r.predicted_label,
                "true_label": r.true_label,
                "visual_contribution_pct": r.visual_contribution_pct,
                "audio_contribution_pct": r.audio_contribution_pct,
                "cmas_score": r.cmas_score,
            }
            for r in all_attributions
        ]

    Path(cfg["paths"]["results_dir"]).mkdir(parents=True, exist_ok=True)
    out_path = os.path.join(cfg["paths"]["results_dir"], "results.json")
    with open(out_path, "w") as f:
        json.dump(metrics, f, indent=2)
    logger.info(f"Wrote {out_path}")

    report_path = os.path.join(cfg["paths"]["results_dir"], "metrics_report.txt")
    with open(report_path, "w") as f:
        f.write(f"CMAS Deepfake Detector — Evaluation Report ({mode}, split={args.split})\n")
        f.write("=" * 70 + "\n")
        f.write(f"N samples:  {metrics['n_samples']}\n\n")
        f.write(f"--- Default threshold (argmax / 0.5 on P(FAKE)) ---\n")
        f.write(f"Accuracy:   {metrics['accuracy']:.4f}\n")
        f.write(f"Precision:  {metrics['precision']:.4f}\n")
        f.write(f"Recall:     {metrics['recall']:.4f}\n")
        f.write(f"F1 score:   {metrics['f1']:.4f}\n")
        f.write(f"ROC-AUC:    {metrics['roc_auc']}\n")
        f.write(f"Confusion matrix (rows=true, cols=pred, order=[REAL,FAKE]):\n")
        f.write(f"{np.array(metrics['confusion_matrix'])}\n")
        if "metrics_at_tuned_threshold" in metrics:
            tm = metrics["metrics_at_tuned_threshold"]
            f.write(f"\n--- Tuned threshold ({metrics['tuned_threshold']:.4f}, metric={metrics['tuned_threshold_metric']}, source: {metrics['tuned_threshold_source']}) ---\n")
            if metrics.get("tuned_threshold_is_degenerate"):
                f.write(
                    "*** WARNING: DEGENERATE THRESHOLD — predicts (almost) only one class. "
                    "DO NOT report the numbers below as a real result. ***\n"
                )
            f.write(f"Accuracy:   {tm['accuracy']:.4f}\n")
            f.write(f"Precision:  {tm['precision']:.4f}\n")
            f.write(f"Recall:     {tm['recall']:.4f}\n")
            f.write(f"F1 score:   {tm['f1']:.4f}\n")
            f.write(f"ROC-AUC:    {tm['roc_auc']}  (unchanged — AUC is threshold-independent, shown for reference)\n")
            f.write(f"Confusion matrix (rows=true, cols=pred, order=[REAL,FAKE]):\n")
            f.write(f"{np.array(tm['confusion_matrix'])}\n")
        if "cmas" in metrics:
            f.write(f"\nCMAS mean: {metrics['cmas']['mean_cmas']}\n")
            f.write(f"CMAS std:  {metrics['cmas']['std_cmas']}\n")
            f.write(f"CMAS n:    {metrics['cmas']['n_samples']} (excluded {metrics['cmas']['n_excluded_real']} REAL samples)\n")
    logger.info(f"Wrote {report_path}")

    print(json.dumps({k: v for k, v in metrics.items() if k not in ("roc_curve", "cmas_per_sample")}, indent=2))


if __name__ == "__main__":
    main()
